# Generated by Django 4.1.7 on 2023-03-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_pic', models.ImageField(upload_to='photos')),
                ('website', models.CharField(max_length=50)),
                ('ngo_helpline', models.CharField(max_length=50)),
                ('ngo_desc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_pic', models.ImageField(upload_to='photos')),
                ('event_desc', models.CharField(max_length=100)),
                ('volunteer', models.IntegerField(default=0)),
                ('event_datetime', models.DateTimeField()),
                ('event_location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('role', models.CharField(choices=[('NGO', 'NGO'), ('User', 'User')], max_length=10)),
                ('status', models.CharField(choices=[('0', 'unapproved'), ('1', 'approved')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'unapproved'), ('1', 'approved')], max_length=10)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.event_table')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='event_table',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table'),
        ),
        migrations.CreateModel(
            name='donate_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.detail_table')),
            ],
        ),
        migrations.CreateModel(
            name='donate_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_kg', models.CharField(max_length=100)),
                ('making_datetime', models.DateTimeField()),
                ('expiry_datetime', models.DateTimeField()),
                ('donation_date', models.DateField()),
                ('samplefood_pic', models.ImageField(upload_to='photos')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.detail_table')),
            ],
        ),
        migrations.CreateModel(
            name='donate_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=100)),
                ('suitable_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=10)),
                ('pairs', models.CharField(max_length=100)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.detail_table')),
            ],
        ),
        migrations.CreateModel(
            name='donate_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_desc', models.CharField(max_length=100)),
                ('book_quantity', models.CharField(max_length=100)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.detail_table')),
            ],
        ),
        migrations.AddField(
            model_name='detail_table',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.login_table'),
        ),
    ]
