# Generated by Django 4.1.7 on 2023-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_alter_event_table_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_table',
            name='event_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event_table',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
