# Generated by Django 4.1.7 on 2023-03-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0003_alter_event_table_event_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_table',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='event_table',
            name='event_date',
            field=models.DateField(default='2022-06-06'),
        ),
        migrations.AddField(
            model_name='event_table',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
