# Generated by Django 4.1.7 on 2023-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0004_remove_event_table_event_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_applications',
            name='status',
            field=models.CharField(choices=[('0', 'unapproved'), ('1', 'approved'), ('2', 'rejected')], max_length=10),
        ),
    ]
