# Generated by Django 4.1.7 on 2023-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0005_alter_volunteer_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_applications',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer_applications',
            name='show_interest_button',
            field=models.BooleanField(default=True),
        ),
    ]
