# Generated by Django 4.2.30 on 2026-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login_table',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
