from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.conf import settings
from . import views

urlpatterns = [
   path("", views.index, name="index"),
   path("basic", views.basic, name="basic"),
   path("about", views.about, name="about"),
   path("contact", views.contact, name="contact"),
   path("submitcontact", views.submitcontact, name="submitcontact"),
   path("login", views.login, name="login"),
   path("signup", views.signup, name="signup"),
   path("viewdata", views.viewdata, name="viewdata"),
   path('checkuser', views.checklogin, name='checkuser'),
   path('completeprofile', views.completeprofile, name='completeprofile'),
   path('completeprofilesubmit', views.completeprofilesubmit, name='completeprofilesubmit'),
   path('ngoprofile', views.ngoprofile, name='ngoprofile'),
   path('editprofilengo', views.editprofilengo, name='editprofilengo'),
   path('editprofile', views.editprofile, name='editprofile'),
   path('profile', views.profile, name='profile'),
   path('changepw', views.changepw, name='changepw'),
   path('changedp', views.changedp, name='changedp'),
   path('datasave', views.datasave, name='datasave'),
   path('datasaveuser', views.datasaveuser, name='datasaveuser'),
   path('events', views.events, name='events'),
   path('addevent', views.addevent, name='addevent'),
   path('addeventsubmit', views.addeventsubmit, name='addeventsubmit'),
   path('applyvolunteer', views.applyvolunteer, name='applyvolunteer'),
   path('applyforvol', views.applyforvol, name='applyforvol'),
   path('manageevent', views.manageevent, name='manageevent'),
   path("deleteevent/<int:deid>", views.deleteevent, name="deleteevent"),
   path("viewevents/<int:veid>", views.viewevents, name="viewevents"),
   path("eventsingle/<int:esid>", views.eventsingle, name="eventsingle"),
   path("viewngo/<int:vnid>", views.viewngo, name="viewngo"),
   path("ngodet/<int:ndid>", views.ngodet, name="ngodet"),
   path("beavol/<int:bavid>", views.beavol, name="beavol"),
   path("acceptcan/<int:acid>", views.acceptcan, name="acceptcan"),
   path("rejectcan/<int:rcid>", views.rejectcan, name="rejectcan"),
   path("viewmyapplications", views.viewmyapplications, name="viewmyapplications"),
   path("donateclothes", views.donateclothes, name="donateclothes"),
   path("donateclothessubmit", views.donateclothessubmit, name="donateclothessubmit"),
   path("donatebooks", views.donatebooks, name="donatebooks"),
   path("donatebooksubmit", views.donatebooksubmit, name="donatebooksubmit"),
   path("donatefood", views.donatefood, name="donatefood"),
   path("donatefoodsubmit", views.donatefoodsubmit, name="donatefoodsubmit"),
   path("donatemoney", views.donatemoney, name="donatemoney"),
   path("donatemoneysubmit", views.donatemoneysubmit, name="donatemoneysubmit"),
   path("receivedmoney", views.receivedmoney, name="receivedmoney"),
   path("receivedfood", views.receivedfood, name="receivedfood"),
   path("receivedclothes", views.receivedclothes, name="receivedclothes"),
   path("receivedbooks", views.receivedbooks, name="receivedbooks"),
   path("reqcan", views.reqcan, name="reqcan"),
   path("reqcansubmit", views.reqcansubmit, name="reqcansubmit"),
   path("allngo", views.allngo, name="allngo"),
   path("viewcan", views.viewcan, name="viewcan"),
   path('logout', views.logout, name='logout'),
   path('social-auth/', include('social_django.urls', namespace='social')),
]